image_xscale =-1;
Obj_pj.reset_frame = true;
//max_hp = irandom_range(1, 4);
max_hp = 10;
hp = max_hp;
is_dead = false;
max_time = 40;
time = max_time;
time_allowed = true;
	draw_set_font(Font_base);
